baseurl = "/"
languageCode = "en-us"
title = "Tasty Licks"

[params]
  description = "An example website for restaurants built by [@eliwilliamson](https://github.com/eliwilliamson) using [Victor Hugo](https://github.com/netlify/victor-hugo)."

[[menu.main]]
    name = "Food"
    url  = "/food/index.html"
    weight = 1
[[menu.main]]
    name = "Drinks"
    url  = "/drinks/index.html"
    weight = 2
[[menu.main]]
    name = "About"
    url  = "/about/index.html"
    weight = 3
[[menu.main]]
    name = "Gallery"
    url  = "/gallery/index.html"
    weight = 4
[[menu.main]]
     name = "Make A Reservation"
     url  = "/contact/index.html"
     weight = 5
