#!/bin/sh
echo Installing curl...
apk add --no-cache curl
echo Downloading hugo...
curl -L https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_0.74.3_Linux-32bit.tar.gz | tar -xz /usr/local/bin
echo Installing Gulp CLI...
npm install -g gulp-cli
echo Running NPM install...
npm install
